display dialog "A Virus Has Been Detected" buttons {"Destroy Virus", "Crash CPU (Risky)"} default button 1

if the button returned of the result is "Destroy Virus" then
display dialog "haha" buttons {"Oh No", "Ok"} default button 1
set volume 7
say "you cannot destroy me"
display dialog "trying attempt 2" buttons {"Oh No", "Ok"} default button 1
set volume 7
beep
display dialog "trying last attempt" buttons {"Oh No", "Ok"} default button 1
set volume 7
beep
say "Virus Upload Complete"
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"NOOO", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"NOOO", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"NOOO", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "Spreading Virus" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep
display dialog "@ERROR274520" buttons {"Help", "Ok"} default button 2
set volume 7
beep

display dialog "Thanks For Your Help" buttons {"You're Welcome :)", "Damn You :@"} default button 1

else
display dialog "Good Move"
end if
